apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-app
  labels:
    app: api-gateway-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: api-gateway-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: api-gateway-app
    spec:
      containers:
        - name: api-gateway-app
          image: yky32/api-gateway:1.0-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 9191

---

apiVersion: v1
kind: Service
metadata:
  name: api-gateway-svc
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "quinsic-cert" #https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/master/docs/controllers/services/examples/https-with-cert-nginx-minimal.yml
spec:
  type: LoadBalancer
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 9191
  selector:
    app: api-gateway-app