apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config-server-app
  labels:
    app: cloud-config-server-app
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: cloud-config-server-app
  template:
    metadata:
      labels:
        app: cloud-config-server-app
    spec:
      containers:
        - name: cloud-config-server-app
          image: yky32/cloud-config-server:1.0-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 9296
            
---

apiVersion: v1
kind: Service
metadata:
  name: cloud-config-server-svc
spec:
  selector:
    app: cloud-config-server-app
  ports:
  - port: 80
    targetPort: 9296