apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service-app
  labels:
    app: profile-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-service-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: profile-service-app
    spec:
      containers:
        - name: profile-service-app
          image: yky32/profile-service:1.0-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 9001
            
---

apiVersion: v1
kind: Service
metadata:
  name: profile-service-svc
spec:
  selector:
    app: profile-service-app
  ports:
  - port: 80
    targetPort: 9001