apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-app
  labels:
    app: user-service-app
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: user-service-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge:  1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: user-service-app
    spec:
      containers:
        - name: user-service-app
          image: yky32/user-service:1.0-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 9002
            
---

apiVersion: v1
kind: Service
metadata:
  name: user-service-svc
spec:
  selector:
    app: user-service-app
  ports:
  - port: 80
    targetPort: 9002