server:
    port: 9003

spring:
    application:
        name: BOOKING-SERVICE
    zipkin:
        base-url: http://127.0.0.1:9411/
    datasource:
        url: jdbc:postgresql://yky32.asuscomm.com:5435/tgt-biz
        username: postgres
        password: postgres
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update

eureka:
    instance:
        preferIpAddress: true
        hostname: eureka-0
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka