server:
  port: 9002

spring:
  application:
    name: USER-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/
  datasource:
    url: jdbc:postgresql://yky32.asuscomm.com:5435/tgt-user
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka


# Actuator Basic Info
info:
  application:
    name: ${spring.application.name}
    version: '@project.version@'

management:
  info:
    env:
      enabled: true
  health:
    readinessstate.enabled: true
    livenessstate.enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus: # Close the default prometheus endpoint and create your own
      enabled: true
    gateway:
      enabled: true
    health:
      probes.enabled: true
      show-details: always
# Actuator Basic Info