eureka:
    instance:
        preferIpAddress: true
        hostname: eureka-0
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka

server:
    port: 9002

spring:
    application:
        name: USER-SERVICE
    datasource:
        url: jdbc:postgresql://yky32.asuscomm.com:5435/tgt-user
        username: postgres
        password: postgres
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
