server:
    port: 9001

spring:
    application:
        name: PROFILE-SERVICE
    datasource:
        url: jdbc:postgresql://yky32.asuscomm.com:5435/tgt-profile
        username: postgres
        password: postgres
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
